version: "3.0"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
#    networks:
#      - essay-network

#  spring-boot-app:
#    image: organicbox-api:latest
#    container_name: organicbox-api
#    ports:
#      - "8080:8080"
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#    depends_on:
#      - redis
#    networks:
#      - essay-network
#    environment:
#      SPRING_REDIS_HOST: localhost
#      SPRING_REDIS_PORT: 6379

#networks:
#  essay-network: